model:
  embedding_output_dim: 512
  use_film: true
  film_context_size: 768
  use_token_learner: true
  num_output_tokens: 1
  vision_model: "efficientnet_b3"
  vision_model_weights: "EfficientNet_B3_Weights"
training:
  learning_rate: 1e-4
  weight_decay: 0.01
trainer:
  default_root_dir: "./runs"
  fast_dev_run: False
  max_epochs: 30
  gradient_clip_val: 1.0
  val_check_interval: 1.0
  log_every_n_steps: 1
logger:
  project: "EfficientNet-RoboCasa-Camera-Contrastive"
  log_model: "all"
  save_dir: "./runs"
  name: "01"
dataloader: 
  batch_size: 32
  validation_percentage: 0.2
  num_workers: 8
data:
  language_encoder: "clip"
  validate: false
  action_keys:
  - actions
  dataset_keys:
  - actions
  action_config:
    actions:
      normalization: 
    action_dict/abs_pos:
      normalization: min_max
    action_dict/abs_rot_axis_angle:
      normalization: min_max
      format: rot_axis_angle
    action_dict/abs_rot_6d:
      normalization: 
      format: rot_6d
    action_dict/rel_pos:
      normalization: 
    action_dict/rel_rot_axis_angle:
      normalization: 
      format: rot_axis_angle
    action_dict/rel_rot_6d:
      normalization: 
      format: rot_6d
    action_dict/gripper:
      normalization: 
    action_dict/base_mode:
      normalization: 
  all_obs_keys:
  - robot0_agentview_left_image
  - robot0_agentview_right_image
  seq_length: 1
  pad_seq_length: false
  frame_stack: 1
  pad_frame_stack: false
  hdf5_normalize_obs: false
  hdf5_load_next_obs: false
  hdf5_cache_mode: 
  hdf5_use_swmr: true
  goal_mode: 
  shuffled_obs_key_groups: 
  hdf5_filter_key: 
  hdf5_validation_filter_key: 
  data_format: robomimic
  data:
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToCab/2024-04-24/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCabToCounter/2024-04-24/demo_gentex_im128_randcams.hdf5"
  - horizon: 700
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToSink/2024-04-25/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPSinkToCounter/2024-04-26_2/demo_gentex_im128_randcams.hdf5"
  - horizon: 600
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToMicrowave/2024-04-27/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPMicrowaveToCounter/2024-04-26/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToStove/2024-04-26/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPStoveToCounter/2024-05-01/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_doors/OpenSingleDoor/2024-04-24/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_doors/CloseSingleDoor/2024-04-24/demo_gentex_im128_randcams.hdf5"
  - horizon: 1000
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_doors/OpenDoubleDoor/2024-04-26/demo_gentex_im128_randcams.hdf5"
  - horizon: 700
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_doors/CloseDoubleDoor/2024-04-29/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_drawer/OpenDrawer/2024-05-03/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_drawer/CloseDrawer/2024-04-30/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_sink/TurnOnSinkFaucet/2024-04-25/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_sink/TurnOffSinkFaucet/2024-04-25/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_sink/TurnSinkSpout/2024-04-29/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_stove/TurnOnStove/2024-05-02/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_stove/TurnOffStove/2024-05-02/demo_gentex_im128_randcams.hdf5"
  - horizon: 600
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_coffee/CoffeeSetupMug/2024-04-25/demo_gentex_im128_randcams.hdf5"
  - horizon: 600
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_coffee/CoffeeServeMug/2024-05-01/demo_gentex_im128_randcams.hdf5"
  - horizon: 300
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_coffee/CoffeePressButton/2024-04-25/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_microwave/TurnOnMicrowave/2024-04-25/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 50_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_microwave/TurnOffMicrowave/2024-04-25/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToCab/mg/2024-05-04-22-12-27_and_2024-05-07-07-39-33/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCabToCounter/mg/2024-07-12-04-33-29/demo_gentex_im128_randcams.hdf5"
  - horizon: 700
    do_eval: true
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToSink/mg/2024-05-04-22-14-06_and_2024-05-07-07-40-17/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPSinkToCounter/mg/2024-05-04-22-14-34_and_2024-05-07-07-40-21/demo_gentex_im128_randcams.hdf5"
  - horizon: 600
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToMicrowave/mg/2024-05-04-22-13-21_and_2024-05-07-07-41-17/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPMicrowaveToCounter/mg/2024-05-04-22-14-26_and_2024-05-07-07-41-42/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToStove/mg/2024-05-04-22-14-20/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPStoveToCounter/mg/2024-05-04-22-14-40/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_doors/OpenSingleDoor/mg/2024-05-04-22-37-39/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_doors/CloseSingleDoor/mg/2024-05-04-22-34-56/demo_gentex_im128_randcams.hdf5"
  - horizon: 1000
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_doors/OpenDoubleDoor/mg/2024-05-04-22-35-53/demo_gentex_im128_randcams.hdf5"
  - horizon: 700
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_doors/CloseDoubleDoor/mg/2024-05-04-22-22-42_and_2024-05-08-06-02-36/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_drawer/OpenDrawer/mg/2024-05-04-22-38-42/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_drawer/CloseDrawer/mg/2024-05-09-09-32-19/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_sink/TurnOnSinkFaucet/mg/2024-05-04-22-17-46/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_sink/TurnOffSinkFaucet/mg/2024-05-04-22-17-26/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_sink/TurnSinkSpout/mg/2024-05-09-09-31-12/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_stove/TurnOnStove/mg/2024-05-08-09-20-31/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_stove/TurnOffStove/mg/2024-05-08-09-20-45/demo_gentex_im128_randcams.hdf5"
  - horizon: 600
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_coffee/CoffeeSetupMug/mg/2024-05-04-22-22-13_and_2024-05-08-05-52-13/demo_gentex_im128_randcams.hdf5"
  - horizon: 600
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_coffee/CoffeeServeMug/mg/2024-05-04-22-21-50/demo_gentex_im128_randcams.hdf5"
  - horizon: 300
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_coffee/CoffeePressButton/mg/2024-05-04-22-21-32/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_microwave/TurnOnMicrowave/mg/2024-05-04-22-40-00/demo_gentex_im128_randcams.hdf5"
  - horizon: 500
    do_eval: false
    filter_key: 3000_demos
    path: "/home/liris/bmachado/robocasa/datasets/v0.1/single_stage/kitchen_microwave/TurnOffMicrowave/mg/2024-05-04-22-39-23/demo_gentex_im128_randcams.hdf5"